const DEFAULT_GREEDY_PARAMS = {
    max_new_tokens: 50,
    num_beams: 1,
    temperature: 1,
    top_k: 0,
    do_sample: false
}

export const TASK_DEFAULT_PARAMS = {
    'translation': DEFAULT_GREEDY_PARAMS,
    'automatic-speech-recognition': DEFAULT_GREEDY_PARAMS,
};

export const NER_TAGS = {
    'ORG': ['#115E59', '#CCFBF1', '#14B8A6'],
    'PER': ['#9D174D', '#FCE7F3', '#EC4899'],
    'LOC': ['#86198F', '#FAE8FF', '#D946EF'],
}

export const COLOURS = [
    '255, 99, 132',
    '54, 162, 235',
    '255, 206, 86',
    '75, 192, 192',
    '153, 102, 255',
    '255, 159, 64',
]

export const LANGUAGE = [
    { "ace_Arab": "Aceh (Arabic)" },
    { "ace_Latn": "Aceh (Latin)" },
    { "acm_Arab": "Arabic (Maltese)" },
    { "acq_Arab": "Acquese (Arabic)" },
    { "aeb_Arab": "Arabic (Tunisian)" },
    { "afr_Latn": "Afrikaans (Latin)" },
    { "ajp_Arab": "Arabic (Moroccan)" },
    { "aka_Latn": "Akan (Latin)" },
    { "amh_Ethi": "Amharic (Ethiopic)" },
    { "apc_Arab": "Arabic (Chadian)" },
    { "arb_Arab": "Arabic (Standard)" },
    { "ars_Arab": "Arabic (Najdi)" },
    { "ary_Arab": "Arabic (Western)" },
    { "arz_Arab": "Arabic (Egyptian)" },
    { "asm_Beng": "Assamese (Bengali)" },
    { "ast_Latn": "Asturian (Latin)" },
    { "awa_Deva": "Awadhi (Devanagari)" },
    { "ayr_Latn": "Aymara (Latin)" },
    { "azb_Arab": "Azerbaijani (Arabic)" },
    { "azj_Latn": "Azerbaijani (Latin)" },
    { "bak_Cyrl": "Bashkir (Cyrillic)" },
    { "bam_Latn": "Bambara (Latin)" },
    { "ban_Latn": "Balinese (Latin)" },
    { "bel_Cyrl": "Belarusian (Cyrillic)" },
    { "bem_Latn": "Bemba (Latin)" },
    { "ben_Beng": "Bengali (Bengali)" },
    { "bho_Deva": "Bhojpuri (Devanagari)" },
    { "bjn_Arab": "Buginese (Arabic)" },
    { "bjn_Latn": "Buginese (Latin)" },
    { "bod_Tibt": "Tibetan (Tibetan)" },
    { "bos_Latn": "Bosnian (Latin)" },
    { "bug_Latn": "Buginese (Latin)" },
    { "bul_Cyrl": "Bulgarian (Cyrillic)" },
    { "cat_Latn": "Catalan (Latin)" },
    { "ceb_Latn": "Cebuano (Latin)" },
    { "ces_Latn": "Czech (Latin)" },
    { "cjk_Latn": "Chinese (CJK)" },
    { "ckb_Arab": "Kurdish (Sorani)" },
    { "crh_Latn": "Crimean Tatar (Latin)" },
    { "cym_Latn": "Welsh (Latin)" },
    { "dan_Latn": "Danish (Latin)" },
    { "deu_Latn": "German (Latin)" },
    { "dik_Latn": "Digo (Latin)" },
    { "dyu_Latn": "Dyula (Latin)" },
    { "dzo_Tibt": "Dzongkha (Tibetan)" },
    { "ell_Grek": "Greek (Greek)" },
    { "eng_Latn": "English (Latin)" },
    { "epo_Latn": "Esperanto (Latin)" },
    { "est_Latn": "Estonian (Latin)" },
    { "eus_Latn": "Basque (Latin)" },
    { "ewe_Latn": "Ewe (Latin)" },
    { "fao_Latn": "Faroese (Latin)" },
    { "pes_Arab": "Persian (Arabic)" },
    { "fij_Latn": "Fijian (Latin)" },
    { "fin_Latn": "Finnish (Latin)" },
    { "fon_Latn": "Fon (Latin)" },
    { "fra_Latn": "French (Latin)" },
    { "fur_Latn": "Friulian (Latin)" },
    { "fuv_Latn": "Fulah (Latin)" },
    { "gla_Latn": "Scottish Gaelic (Latin)" },
    { "gle_Latn": "Irish (Latin)" },
    { "glg_Latn": "Galician (Latin)" },
    { "grn_Latn": "Guarani (Latin)" },
    { "guj_Gujr": "Gujarati (Gujarati)" },
    { "hat_Latn": "Haitian Creole (Latin)" },
    { "hau_Latn": "Hausa (Latin)" },
    { "heb_Hebr": "Hebrew (Hebrew)" },
    { "hin_Deva": "Hindi (Devanagari)" },
    { "hne_Deva": "Chhattisgarhi (Devanagari)" },
    { "hrv_Latn": "Croatian (Latin)" },
    { "hun_Latn": "Hungarian (Latin)" },
    { "hye_Armn": "Armenian (Armenian)" },
    { "ibo_Latn": "Igbo (Latin)" },
    { "ilo_Latn": "Ilokano (Latin)" },
    { "ind_Latn": "Indonesian (Latin)" },
    { "isl_Latn": "Icelandic (Latin)" },
    { "ita_Latn": "Italian (Latin)" },
    { "jav_Latn": "Javanese (Latin)" },
    { "jpn_Jpan": "Japanese (Japanese)" },
    { "kab_Latn": "Kabyle (Latin)" },
    { "kac_Latn": "Kachin (Latin)" },
    { "kam_Latn": "Kamba (Latin)" },
    { "kan_Knda": "Kannada (Kannada)" },
    { "kas_Arab": "Kashmiri (Arabic)" },
    { "kas_Deva": "Kashmiri (Devanagari)" },
    { "kat_Geor": "Georgian (Georgian)" },
    { "knc_Arab": "Kangri (Arabic)" },
    { "knc_Latn": "Kangri (Latin)" },
    { "kaz_Cyrl": "Kazakh (Cyrillic)" },
    { "kbp_Latn": "Kabuverdianu (Latin)" },
    { "kea_Latn": "Kabuverdianu (Latin)" },
    { "khm_Khmr": "Khmer (Khmer)" },
    { "kik_Latn": "Kikuyu (Latin)" },
    { "kin_Latn": "Kinyarwanda (Latin)" },
    { "kir_Cyrl": "Kyrgyz (Cyrillic)" },
    { "kmb_Latn": "Kimbundu (Latin)" },
    { "kon_Latn": "Kongo (Latin)" },
    { "kor_Hang": "Korean (Hangul)" },
    { "kmr_Latn": "Kurdish (Latin)" },
    { "lao_Laoo": "Lao (Lao)" },
    { "lvs_Latn": "Latvian (Latin)" },
    { "lij_Latn": "Ligurian (Latin)" },
    { "lim_Latn": "Limburgish (Latin)" },
    { "lin_Latn": "Lingala (Latin)" },
    { "lit_Latn": "Lithuanian (Latin)" },
    { "lmo_Latn": "Lombard (Latin)" },
    { "ltg_Latn": "Latgalian (Latin)" },
    { "ltz_Latn": "Luxembourgish (Latin)" },
    { "lua_Latn": "Luba-Katanga (Latin)" },
    { "lug_Latn": "Ganda (Latin)" },
    { "luo_Latn": "Luo (Latin)" },
    { "lus_Latn": "Mizo (Latin)" },
    { "mag_Deva": "Magahi (Devanagari)" },
    { "mai_Deva": "Maithili (Devanagari)" },
    { "mal_Mlym": "Malayalam (Malayalam)" },
    { "mar_Deva": "Marathi (Devanagari)" },
    { "min_Latn": "Minangkabau (Latin)" },
    { "mkd_Cyrl": "Macedonian (Cyrillic)" },
    { "plt_Latn": "Polish (Latin)" },
    { "mlt_Latn": "Maltese (Latin)" },
    { "mni_Beng": "Manipuri (Bengali)" },
    { "khk_Cyrl": "Khakas (Cyrillic)" },
    { "mos_Latn": "Mossi (Latin)" },
    { "mri_Latn": "Māori (Latin)" },
    { "zsm_Latn": "Malay (Latin)" },
    { "mya_Mymr": "Burmese (Myanmar)" },
    { "nld_Latn": "Dutch (Latin)" },
    { "nno_Latn": "Norwegian (Nynorsk, Latin)" },
    { "nob_Latn": "Norwegian (Bokmål, Latin)" },
    { "npi_Deva": "Nepali (Devanagari)" },
    { "nso_Latn": "Northern Sotho (Latin)" },
    { "nus_Latn": "Nuer (Latin)" },
    { "nya_Latn": "Nyanja (Latin)" },
    { "oci_Latn": "Occitan (Latin)" },
    { "gaz_Latn": "Ganda (Latin)" },
    { "ory_Orya": "Odia (Orya)" },
    { "pag_Latn": "Pangasinan (Latin)" },
    { "pan_Guru": "Punjabi (Gurmukhi)" },
    { "pap_Latn": "Papiamento (Latin)" },
    { "pol_Latn": "Polish (Latin)" },
    { "por_Latn": "Portuguese (Latin)" },
    { "prs_Arab": "Persian (Arabic)" },
    { "pbt_Arab": "Pashto (Arabic)" },
    { "quy_Latn": "Quechua (Latin)" },
    { "ron_Latn": "Romanian (Latin)" },
    { "run_Latn": "Rundi (Latin)" },
    { "rus_Cyrl": "Russian (Cyrillic)" },
    { "sag_Latn": "Sango (Latin)" },
    { "san_Deva": "Sanskrit (Devanagari)" },
    { "sat_Beng": "Santali (Bengali)" },
    { "scn_Latn": "Sicilian (Latin)" },
    { "shn_Mymr": "Shan (Myanmar)" },
    { "sin_Sinh": "Sinhala (Sinhala)" },
    { "slk_Latn": "Slovak (Latin)" },
    { "slv_Latn": "Slovenian (Latin)" },
    { "snd_Arab": "Sindhi (Arabic)" },
    { "som_Latn": "Somali (Latin)" },
    { "sqi_Latn": "Albanian (Latin)" },
    { "srd_Latn": "Sardinian (Latin)" },
    { "srp_Cyrl": "Serbian (Cyrillic)" },
    { "ssw_Latn": "Swati (Latin)" },
    { "swa_Latn": "Swahili (Latin)" },
    { "swe_Latn": "Swedish (Latin)" },
    { "tam_Taml": "Tamil (Tamil)" },
    { "tat_Cyrl": "Tatar (Cyrillic)" },
    { "tel_Telu": "Telugu (Telugu)" },
    { "tgk_Cyrl": "Tajik (Cyrillic)" },
    { "tha_Tahi": "Thai (Thai)" },
    { "tir_Ethi": "Tigrinya (Ethiopic)" },
    { "ton_Latn": "Tongan (Latin)" },
    { "tsn_Latn": "Tswana (Latin)" },
    { "tso_Latn": "Tsonga (Latin)" },
    { "tuk_Latn": "Turkmen (Latin)" },
    { "tur_Latn": "Turkish (Latin)" },
    { "tvl_Latn": "Tuvalu (Latin)" },
    { "udm_Cyrl": "Udmurt (Cyrillic)" },
    { "uig_Latn": "Uighur (Latin)" },
    { "ukr_Cyrl": "Ukrainian (Cyrillic)" },
    { "urd_Arab": "Urdu (Arabic)" },
    { "uzb_Latn": "Uzbek (Latin)" },
    { "vie_Latn": "Vietnamese (Latin)" },
    { "vol_Latn": "Volapük (Latin)" },
    { "war_Latn": "Waray (Latin)" },
    { "wln_Latn": "Walloon (Latin)" },
    { "xho_Latn": "Xhosa (Latin)" },
    { "yid_Hebr": "Yiddish (Hebrew)" },
    { "yor_Latn": "Yoruba (Latin)" },
    { "zho_Hans": "Chinese (Simplified)" },
    { "zho_Hant": "Chinese (Traditional)" },
    { "zul_Latn": "Zulu (Latin)" }
]